name: Deploy Release to Cloudflare Pages

# This workflow runs ONLY when you publish a new Release in GitHub.
# It ignores normal pushes to main.
# on:
#   release:
#     types: [published]
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout Vault
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download Latest Kiln Binary
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/otaleghani/kiln/releases/latest | jq -r .tag_name)
          if [ "$LATEST_TAG" == "null" ]; then
            echo "Error: Could not find a latest release."
            exit 1
          fi
          echo "Detected latest Kiln version: $LATEST_TAG"
          URL="https://github.com/otaleghani/kiln/releases/download/${LATEST_TAG}/kiln_linux_amd64"
          echo "Downloading from $URL..."
          sudo curl -L -o /usr/local/bin/kiln $URL
          sudo chmod +x /usr/local/bin/kiln
          kiln --help

      - name: Build Site
        run: |
          echo "Building release ${{ github.event.release.tag_name }}"
          kiln generate \
            --input ./docs \
            --output ./public \
            --flat-urls=true \
            --url "https://mysite.pages.dev"

      # Publish to Cloudflare Pages
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kiln-documentation
          directory: public
          commitMessage: "Deploying Release ${{ github.event.release.tag_name }}"
